### ISSUE TITLE
Error When saving Model trained with darkstorm2150/Protogen_x5.8_Official_Release

### ISSUE THREAD

**Issue by imasubmarine** [geocine/sd-easy-mode#3] opened 2023-02-04 12:22 UTC
```
Steps: 100% 3003/3003 [42:14<00:00,  1.18it/s, loss=0.246, lr=1e-6]
Traceback (most recent call last):
 File "train_dreambooth.py", line 869, in <module>
    main(args)
  File "train_dreambooth.py", line 862, in main
    save_weights(global_step)
  File "train_dreambooth.py", line 720, in save_weights
    text_enc_model = accelerator.unwrap_model(text_encoder, keep_fp32_wrapper=True)
TypeError: unwrap_model() got an unexpected keyword argument 'keep_fp32_wrapper'
```

Any idea ?

**Comment by geocine** [comment] 2023-02-04 13:05
When did you try this? I had this error 18 hours ago and fixed it. Can you retry using the link in this repo 

> https://colab.research.google.com/github/geocine/sd-easy-mode/blob/main/EasyMode_Stable_Diffusion.ipynb

Also click on Runtime > Disconnect and Delete Runtime to make sure you are in new state

**Comment by imasubmarine** [comment] 2023-02-04 13:07
Thanks ! That's exactly what i'm doing right now.

**Comment by imasubmarine** [comment] 2023-02-04 14:11
Thanks again ! No more errors with the last version.
But it still cannot save the model

```
Reshaping encoder.mid.attn_1.q.weight for SD format
Reshaping encoder.mid.attn_1.k.weight for SD format
Reshaping encoder.mid.attn_1.v.weight for SD format
Reshaping encoder.mid.attn_1.proj_out.weight for SD format
Reshaping decoder.mid.attn_1.q.weight for SD format
Reshaping decoder.mid.attn_1.k.weight for SD format
Reshaping decoder.mid.attn_1.v.weight for SD format
Reshaping decoder.mid.attn_1.proj_out.weight for SD format
^C
[*] Converted ckpt saved at /content/stable_diffusion_models/zwx/2889/model.ckpt
cp: cannot stat '/content/stable_diffusion_models/zwx/2889/model.ckpt': No such file or directory
Model saved at /-woman-2889-zwx.ckpt Wait for 5 minutes before closing
To use your model on other applications make sure to mention "zwx woman" in the prompt.
```

**Comment by geocine** [comment] 2023-02-04 15:11
I tried this model and was able to save `darkstorm2150/Protogen_x5.8_Official_Release` . I cannot reproduce your issue for now but I will keep on trying so I can fix it.

**Comment by geocine** [comment] 2023-02-04 15:27
@imasubmarine  For now, can you trying running the `Free runtime memory` then re-run the `Save` block again

**Comment by geocine** [comment] 2023-02-04 20:47
This should be fixed now. I also created a video just in case 

https://user-images.githubusercontent.com/507464/216788746-789f81e9-efb0-4b70-9afa-97216d5fdb19.mp4

**Closed by geocine** 2023-02-04 20:47 UTC
